graph TD
    subgraph Controller Layer
        TaskController
    end

    subgraph Service Layer
        TaskService
    end

    subgraph Repository Layer
        TaskRepository
    end

    subgraph DTOs
        TaskRequestDTO
        TaskResponseDTO
        TaskMapper
    end

    subgraph Model
        TaskModels
    end

    %% Relationships
    TaskController -->|Uses| TaskService
    TaskService -->|Uses| TaskRepository
    TaskService -->|Converts| TaskMapper
    TaskMapper -->|Maps To| TaskRequestDTO
    TaskMapper -->|Maps To| TaskResponseDTO
    TaskMapper -->|Maps To| TaskModels
    TaskRepository -->|Persists| TaskModels
